---
- name: Merge Kubeconfig
  vars_files:
    - "vars/{{ k8s_cluster_name }}_cluster.yml"
  hosts: vm_host
  tasks:
    
    - name: Replace common name kubernetes with the cluster name
      ansible.builtin.replace:
        path: "{{ workspace_directory.base_path }}/clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
        regexp: 'kubernetes'
        replace: "{{ k8s.cluster_name }}"
    
    - name: Merge kubeconfig
      ansible.builtin.shell: |
        export KUBECONFIG=~/.kube/config:{{ workspace_directory.base_path }}/clusters/{{ k8s.cluster_name }}/admin.kubeconfig
        kubectl config view --flatten > /tmp/all-in-one-kubeconfig.yaml
        mv /tmp/all-in-one-kubeconfig.yaml ~/.kube/config
        rm -f /tmp/all-in-one-kubeconfig.yaml
        export KUBECONFIG=~/.kube/config
      when: k8s.merge_kubeconfig